### ISSUE TITLE
Continuous buffer revert

### ISSUE THREAD

**Issue by arichiardi** [magoyette/openapi-yaml-mode#2]
Dear maintainer, I just started using this package, thanks for it, I think the formatting really looks better than `yaml-mode`.

I have a huge `openapi.yaml` with one `$ref` per route like this:

```yaml
  /api/v1/measurements:
    $ref: 'foo/api-v1-measurements-submit.yaml'
```

Whenever I revert the buffer or enable `openapi-yaml-mode` Emacs freezes and this is what I get from `profiles-start`\`profiler-report`:

```
     75749  98% - command-execute
       75749  98%  - call-interactively
       75749  98%   - funcall-interactively
       75749  98%    - revert-buffer-quick
       75749  98%     - revert-buffer
       75749  98%      - revert-buffer--default
       75748  98%       - after-find-file
       75740  98%        + normal-mode
           8   0%        + run-hooks
           1   0%       - file-truename
           1   0%        - file-truename
           1   0%         - file-truename
           1   0%          - file-truename
           1   0%           - file-truename
           1   0%            - file-truename
           1   0%               file-truename
        1168   1% - ...
        1163   1%  + git-gutter:live-update
           4   0%  + helm-comp-read
           1   0%  + magit-rev-parse-safe
           0   0%    Automatic GC
```

Because of that rendering takes >10s, which is not ideal.

I wish I could help but don't have much time on my hand at the moment, but please let me know if you want me to try anything on my side, thank you!

**Comment by magoyette** [comment]
I'm archiving this repository since I'm no longer using openapi-yaml-mode and don't plan to maintain it.
